### ISSUE TITLE
关于显存占用问题

### ISSUE THREAD

**Issue by ouguozhen** [MhLiao/DB#75]
你好，有个问题想请教一下
测试显卡：1080Ti
我用了8k+张图片来测试，发现一开始的时候占用的显存只有2000M+，过一段时间之后升到4000M+,最大的占用会到5000M+，并且占用的显存增大之后不会降下来，请问这是什么原因呢？是没有及时释放吗，并且有的时候感觉都不用GPU了，前向推理速度会达到1s

**Comment by ouguozhen** [comment]
补充：
num_workers被我设置为1

**Comment by MhLiao** [comment]
@ouguozhen 我近期检查一下看看是否是inference的代码有问题

**Comment by ouguozhen** [comment]
@MhLiao 期待你的回答，我目前通过每次前向计算之后都清空占用的显存是暂时解决了这个问题

**Comment by 562841850** [comment]
hi @ouguozhen @MhLiao ，我现在训练会报“CUDA out of memory”，batch_size和num_workers都设置为1，仍然报显存溢出，请问这个是什么原因？怎么解决呢，谢谢

**Comment by hhhhhhogan** [comment]
> hi @ouguozhen @MhLiao ，我现在训练会报“CUDA out of memory”，batch_size和num_workers都设置为1，仍然报显存溢出，请问这个是什么原因？怎么解决呢，谢谢

请问你解决这个显存占用的问题了吗？我这边也遇到了

**Comment by congjianting** [comment]
num_workers=0 try @hhhhhhogan

**Comment by Gavinic** [comment]
请问这个Bug解决了吗？Inference 的时候内存一直增加

**Comment by longnanxi** [comment]
> 请问这个Bug解决了吗？Inference 的时候内存一直增加

请问您解决了内存一直增加啊的问题了吗？期待您的回复
